<a href="https://colab.research.google.com/github/enjoycodingwithdhruv/Python_Tut/blob/master/numpy_part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!pip install numpy

In [0]:
import numpy as np

In [0]:
#Arrays

In [0]:
#Using List

In [0]:
x = np.array([1,2,3,4])

In [10]:
x

array([1, 2, 3, 4])

In [0]:
#Using tuple

In [0]:
a = np.array((2,4,6,8))

In [13]:
a

array([2, 4, 6, 8])

In [0]:
#np.zeros

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
#np.ones

In [18]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
np.ones( (3,4), dtype=np.int16 )

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [0]:
#np.empty

In [23]:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [0]:
#np.arange

In [34]:
np.arange( 10, 40, 5)

array([10, 15, 20, 25, 30, 35])

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.arange( 10, 5, -1)

array([10,  9,  8,  7,  6])

In [39]:
np.arange(5, 5)

array([], dtype=int64)

In [0]:
#linspace

In [43]:
np.linspace(0, 5, 9)

array([0.   , 0.625, 1.25 , 1.875, 2.5  , 3.125, 3.75 , 4.375, 5.   ])